fetch_limits:
  referenda: 10
  treasury_spends: 10
  child_bounties: 10
  fellowship_treasury_spends: 10
  fellowship_salary_cycles: 0  # 0 = fetch all, -1 = skip
block_time_projection:
  block_number: 25732485
  block_datetime: 2025-04-25T15:27:36
  block_time: 6.0

